modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/KillerMapper/embellishcraft/issues"
logoFile="embellishcraft-bop_logo.png"
[[mods]]
modId="embellishcraft-bop"
version="${file.jarVersion}"
displayName="EmbellishCraft BoP Addon"
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://mapper.tv/embellishcraft/"
credits="Thanks for Forge devs and modders that let their mods open-source."
authors="Mapper"
description='''EmbellishCraft BOP Addon is an Embellishcraft addon that adds Biomes O'Plenty wood variants to EmbellishCraft's furniture.'''

[[dependencies.embellishcraft-bop]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft-bop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.15.2-10.0.0.353,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="embellishcraft"
    mandatory=true
    versionRange="[1.15.2-2.2,)"
    ordering="NONE"
    side="BOTH"