modLoader="javafml" #mandatory
loaderVersion="[31,)"
issueTrackerURL="https://github.com/KillerMapper/embellishcraft/issues" #optional
logoFile="embellishcraft-bop_logo.png" #optional
[[mods]] #mandatory
modId="embellishcraft-bop" #mandatory
version="${file.jarVersion}" #mandatory
displayName="EmbellishCraft BoP Addon" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://mapper.tv/embellishcraft/" #optional
credits="Thanks for Forge devs and modders that let their mods open-source." #optional
authors="Mapper" #optional
description='''EmbellishCraft BOP Addon is an Embellishcraft addon that adds Biomes O'Plenty wood variants to EmbellishCraft's furniture.'''

[[dependencies.embellishcraft-bop]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft-bop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.15.2-10.0.0.353,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="embellishcraft"
    mandatory=true
    versionRange="[1.15.2-2.1.1,)"
    ordering="NONE"
    side="BOTH"