modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/embellishcraft-bop/issues"
[[mods]]
modId="embellishcraft-bop"
version="${file.jarVersion}"
displayName="EmbellishCraft BoP Addon"
#updateJSONURL="http://myurl.me/" #optional
displayURL="http://mapper.tv/embellishcraft/"
logoFile="embellishcraft-bop_logo.png"
credits="Thanks for Forge devs and modders that let their mods open-source."
authors="Mapper"
description='''EmbellishCraft BOP Addon is an Embellishcraft addon that adds Biomes O'Plenty wood variants to EmbellishCraft's furniture.'''

[[dependencies.embellishcraft-bop]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.embellishcraft-bop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.embellishcraft]]
    modId="mapperbase"
    mandatory=true
    versionRange="[1.16.1-2.0.,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="biomesoplenty"
    mandatory=true
    versionRange="[1.16.1-11.0.0.395,)"
    ordering="AFTER"
    side="BOTH"
    
[[dependencies.embellishcraft-bop]]
    modId="embellishcraft"
    mandatory=true
    versionRange="[1.16.1-3.0,)"
    ordering="AFTER"
    side="BOTH"